name: Build the APK
run-name: Building the openlight_camera.apk
on: [push]
jobs:
  Build-the-APK:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f docker/Dockerfile -t openlight-decomp-tools:latest .

      - name: Download libraries
        run: bash download-libs.sh

      - name: Build APK
        run: |
          docker run --rm --privileged \
            -e PUID="$(id -u)" -e PGID="$(id -g)" \
            -v "$PWD":/repo \
            openlight-decomp-tools:latest \
            make clean apk

      - name: Sign APK
        uses: ookami125/apksigner-android@v1
        id: sign_app
        with:
          releaseDirectory: build
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          customArgs: --v1-signing-enabled,true,--v2-signing-enabled,true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: openlight_camera
          path: build/openlight_camera.apk
